CREATE TABLE IF NOT EXISTS events_similarities (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_a BIGINT NOT NULL,
                    event_b BIGINT NOT NULL,
                    score DOUBLE PRECISION NOT NULL,
                    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS users_actions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    event_id BIGINT NOT NULL,
                    action_type VARCHAR(50) NOT NULL,
                    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
);