application:
  name: collector

server:
  port: 0

grpc:
  server:
    port: 0

collector:
  kafka:
    bootstrap-servers: localhost:9092
    topic: stats.user-actions.v1
    key-serializer: org.apache.kafka.common.serialization.VoidSerializer
    value-serializer: ru.practicum.serializer.CollectorSerializer