server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: default
    availability-zones:
      default: default-zone
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/