server:
  port: 0

spring:
  application:
    name: category-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:55432/category-db
    driver-class-name: "org.postgresql.Driver"
    username: "category-db"
    password: "category_pw"