server:
  port: 0

spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hibernate:
          format_sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:25432/user-db
    driver-class-name: "org.postgresql.Driver"
    username: "user-db"
    password: "user_pw"