server:
  port: 0
stats-server:
  url: "http://stats-server"
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: POSTGRESQL
    #database: H2
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://main-db:5432/explore-main
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:file:./db/request
    username: explore-main
    password: explore-main
logging:
  level:
    org:
      zalando.logbook: TRACE
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
      enableRetry: true
      retryAttempts: 15
      retryDelay: 3000
