CREATE TABLE IF NOT EXISTS requests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id       BIGINT,
    event_id           BIGINT,
    created            TIMESTAMP WITHOUT TIME ZONE,
    status             VARCHAR(16) NOT NULL
);