application:
  name: analyzer

server:
  port: 0

grpc:
  server:
    port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:65432/analyzer-db
    driverClassName: "org.postgresql.Driver"
    username: "analyzer-db"
    password: "analyzer_pw"

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    event-similarity-consumer:
      client-id: events-similarity-consumer
      group-id: events-similarity-group
      topic: stats.events-similarity.v1
      value-deserializer: ru.practicum.deserializer.EventSimilarityDeserializer
    user-actions-consumer:
      client-id: user-actions-consumer
      group-id: user-actions-group
      topic: stats.user-actions.v1
      value-deserializer: ru.practicum.deserializer.UserActionDeserializer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  score:
    view: 0.4
    registration: 0.8
    like: 1
