server:
    port: 0

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:6434/eventdb
        username: postgres
        password: 12345
    cloud:
        openfeign:
            enabled: true
            okhttp:
                enabled: true

discovery:
    services:
        stats-server-id: stat-server

logging:
    level:
        org.springframework.orm.jpa: INFO
        org.springframework.transaction: INFO
        org.springframework.transaction.interceptor: INFO
        org.springframework.orm.jpa.JpaTransactionManager: DEBUG
        org.hibernate.SQL: DEBUG
